### PR TITLE
Dash fixed area improvements

### PR DESCRIPTION
**Pull request by Marginy605**

### CODE REVIEW

**Review by flops — APPROVED** [review]

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10268-dash-fixed-area-improvements-1466/dash-empty-state-view-1466/ru/">dash.empty-state.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10268-dash-fixed-area-improvements-1466/dash-empty-state-view-1466/en/">dash.empty-state.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>Errors occurred when merging changes from your branch with the Weblate branch.</summary>

```
Rebasing (1/2)
Auto-merging src/i18n-keysets/dash.empty-state.view/ru.json
CONFLICT (content): Merge conflict in src/i18n-keysets/dash.empty-state.view/ru.json
error: could not apply 4f725faf... Translated using Weblate (Russian)
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 4f725faf... Translated using Weblate (Russian)
 (1)
```

</details>

**Resolve conflicts according to instructions**
1. Switch to the current branch associated with this pull request.
```
git checkout CHARTS-10268-dash-fixed-area-improvements
```
2. Add Weblate as remote. And remove previous upstream with the same name:
```
git remote remove weblate 2> /dev/null
git remote add weblate https://weblate.gravity-ui.com/git/datalens/charts-10268-dash-fixed-area-improvements-1466/chartkit-1466/
git -c http.sslVerify=false remote update weblate
```
3. Merge Weblate changes:
```
git merge weblate/CHARTS-10268-dash-fixed-area-improvements
```
4. Resolve conflicts:
```
edit ...
git add ...
git commit
```
5. Push changes to upstream repository, Weblate will fetch merge from there:
```
git push origin
```

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10268-dash-fixed-area-improvements-1466/dash-empty-state-view-1466/ru/">dash.empty-state.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10268-dash-fixed-area-improvements-1466/dash-empty-state-view-1466/en/">dash.empty-state.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>Errors occurred when merging changes from your branch with the Weblate branch.</summary>

```
Rebasing (1/3)
Auto-merging src/i18n-keysets/dash.empty-state.view/ru.json
CONFLICT (content): Merge conflict in src/i18n-keysets/dash.empty-state.view/ru.json
error: could not apply dba54a93a... Translated using Weblate (Russian)
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply dba54a93a... Translated using Weblate (Russian)
 (1)
```

</details>

**Resolve conflicts according to instructions**
1. Switch to the current branch associated with this pull request.
```
git checkout CHARTS-10268-dash-fixed-area-improvements
```
2. Add Weblate as remote. And remove previous upstream with the same name:
```
git remote remove weblate 2> /dev/null
git remote add weblate https://weblate.gravity-ui.com/git/datalens/charts-10268-dash-fixed-area-improvements-1466/chartkit-1466/
git -c http.sslVerify=false remote update weblate
```
3. Merge Weblate changes:
```
git merge weblate/CHARTS-10268-dash-fixed-area-improvements
```
4. Resolve conflicts:
```
edit ...
git add ...
git commit
```
5. Push changes to upstream repository, Weblate will fetch merge from there:
```
git push origin
```

**Review by flops — APPROVED** [review]

**Pull request merged**
