### PR TITLE
Add unique fieldName validation for group controls

### PR DESCRIPTION
**Pull request by mournfulCoroner**
Related to https://github.com/datalens-tech/datalens/issues/89

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9511-add-unique-field-name-validation-for-group-866/dash-control-dialog-edit-866/ru/">dash.control-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9511-add-unique-field-name-validation-for-group-866/dash-control-dialog-edit-866/en/">dash.control-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9511-add-unique-field-name-validation-for-group-866/dash-control-dialog-edit-866/ru/">dash.control-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9511-add-unique-field-name-validation-for-group-866/dash-control-dialog-edit-866/en/">dash.control-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9511-add-unique-field-name-validation-for-group-866/dash-control-dialog-edit-866/ru/">dash.control-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9511-add-unique-field-name-validation-for-group-866/dash-control-dialog-edit-866/en/">dash.control-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by flops — DISMISSED** [review]

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>Errors occurred when merging changes from your branch with the Weblate branch.</summary>

```
Rebasing (1/3)
dropping de1df3de9c3871a406572ab26dd3a18e59d7dc8b Translated using Weblate (Russian) -- patch contents already upstream
Rebasing (2/3)
Auto-merging src/i18n-keysets/dash.control-dialog.edit/en.json
CONFLICT (content): Merge conflict in src/i18n-keysets/dash.control-dialog.edit/en.json
error: could not apply db75d358... Translated using Weblate (English)
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply db75d358... Translated using Weblate (English)
 (1)
```

</details>

**Resolve conflicts according to instructions**
1. Switch to the current branch associated with this pull request.
```
git checkout CHARTS-9511-Add-unique-fieldName-validation-for-group
```
2. Add Weblate as remote. And remove previous upstream with the same name:
```
git remote remove weblate 2> /dev/null
git remote add weblate https://weblate.gravity-ui.com/git/datalens/charts-9511-add-unique-field-name-validation-for-group-866/chartkit-866/
git -c http.sslVerify=false remote update weblate
```
3. Merge Weblate changes:
```
git merge weblate/CHARTS-9511-Add-unique-fieldName-validation-for-group
```
4. Resolve conflicts:
```
edit ...
git add ...
git commit
```
5. Push changes to upstream repository, Weblate will fetch merge from there:
```
git push origin
```

**Review by flops — APPROVED** [review]

**Pull request merged**
