### PR TITLE
Support copy and paste selector in selectors group

### PR DESCRIPTION
**Pull request by mournfulCoroner**

### CODE REVIEW

**Comment by mournfulCoroner** [comment]
Related to https://github.com/datalens-tech/datalens/issues/89

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9709-add-paste-btn-in-selector-group-1077/dash-group-controls-dialog-edit-1077/ru/">dash.group-controls-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9709-add-paste-btn-in-selector-group-1077/dash-group-controls-dialog-edit-1077/en/">dash.group-controls-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9709-add-paste-btn-in-selector-group-1077/dash-group-controls-dialog-edit-1077/ru/">dash.group-controls-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9709-add-paste-btn-in-selector-group-1077/dash-group-controls-dialog-edit-1077/en/">dash.group-controls-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9709-add-paste-btn-in-selector-group-1077/dash-group-controls-dialog-edit-1077/ru/">dash.group-controls-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9709-add-paste-btn-in-selector-group-1077/dash-group-controls-dialog-edit-1077/en/">dash.group-controls-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9709-add-paste-btn-in-selector-group-1077/dash-group-controls-dialog-edit-1077/ru/">dash.group-controls-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9709-add-paste-btn-in-selector-group-1077/dash-group-controls-dialog-edit-1077/en/">dash.group-controls-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9709-add-paste-btn-in-selector-group-1077/dash-group-controls-dialog-edit-1077/ru/">dash.group-controls-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9709-add-paste-btn-in-selector-group-1077/dash-group-controls-dialog-edit-1077/en/">dash.group-controls-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by flops — APPROVED** [review]

**Pull request merged**
