### PR TITLE
Fixes in navigation menu

### PR DESCRIPTION
**Pull request by imsitnikov**

### CODE REVIEW

**Review by stankis — APPROVED** [review]

**Review by jhoncool — APPROVED** [review]

**Comment by robot-charts** [comment]
**i18n-check**
The reviewer is still working on checking your i18n changes. Wait for a Pull Request from Weblate.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/component-navigation-view-806/ru/">component.navigation.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/component-navigation-view-806/en/">component.navigation.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/dash-dialogs-common-edit-806/ru/">dash.dialogs-common.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/dash-dialogs-common-edit-806/en/">dash.dialogs-common.edit (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/editor-templates-view-806/ru/">editor.templates.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/editor-templates-view-806/en/">editor.templates.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/component-navigation-view-806/ru/">component.navigation.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/component-navigation-view-806/en/">component.navigation.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/dash-dialogs-common-edit-806/ru/">dash.dialogs-common.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/dash-dialogs-common-edit-806/en/">dash.dialogs-common.edit (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/editor-templates-view-806/ru/">editor.templates.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/editor-templates-view-806/en/">editor.templates.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/component-navigation-view-806/ru/">component.navigation.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9404-fixes-in-navigation-menu-806/component-navigation-view-806/en/">component.navigation.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Pull request merged**
