### PR TITLE
Add link to Yandex Documents in DialogAddDocument

### PR DESCRIPTION
**Pull request by korvin89**
[CHARTS-9020]

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/add-link-to-yadocs-530/connections-yadocs-view-530/en/">connections.yadocs.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/add-link-to-yadocs-530/connections-yadocs-view-530/ru/">connections.yadocs.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/add-link-to-yadocs-530/connections-yadocs-view-530/en/">connections.yadocs.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/add-link-to-yadocs-530/connections-yadocs-view-530/ru/">connections.yadocs.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>Errors occurred when merging changes from your branch with the Weblate branch.</summary>
```
warning: skipped previously applied commit 87b78d0f
warning: skipped previously applied commit a6433e9e
hint: use --reapply-cherry-picks to include skipped commits
hint: Disable this message with "git config advice.skippedCherryPicks false"
Rebasing (1/1)
Auto-merging .lintstagedrc.json
CONFLICT (add/add): Merge conflict in .lintstagedrc.json
Auto-merging src/i18n-keysets/component.dialog-relations.view/en.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/component.dialog-relations.view/en.json
Auto-merging src/i18n-keysets/component.dialog-relations.view/ru.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/component.dialog-relations.view/ru.json
Auto-merging src/i18n-keysets/connections.yadocs.view/en.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/connections.yadocs.view/en.json
Auto-merging src/i18n-keysets/connections.yadocs.view/ru.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/connections.yadocs.view/ru.json
Auto-merging src/i18n-keysets/dash.popup-widgets-order.view/en.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/dash.popup-widgets-order.view/en.json
Auto-merging src/i18n-keysets/dash.popup-widgets-order.view/ru.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/dash.popup-widgets-order.view/ru.json
Auto-merging src/i18n-keysets/dash.text-dialog.edit/en.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/dash.text-dialog.edit/en.json
Auto-merging src/i18n-keysets/dash.text-dialog.edit/ru.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/dash.text-dialog.edit/ru.json
Auto-merging src/i18n-keysets/sql/en.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/sql/en.json
Auto-merging src/i18n-keysets/sql/ru.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/sql/ru.json
Auto-merging src/server/components/charts-engine/controllers/embeds.ts
CONFLICT (add/add): Merge conflict in src/server/components/charts-engine/controllers/embeds.ts
Auto-merging src/server/modes/charts/plugins/datalens/preparers/line-time/index.ts
CONFLICT (add/add): Merge conflict in src/server/modes/charts/plugins/datalens/preparers/line-time/index.ts
Auto-merging src/server/modes/charts/plugins/datalens/preparers/line/helpers/line-mappers/mapDataToLines.ts
CONFLICT (add/add): Merge conflict in src/server/modes/charts/plugins/datalens/preparers/line/helpers/line-mappers/mapDataToLines.ts
Auto-merging src/shared/modules/index.ts
CONFLICT (add/add): Merge conflict in src/shared/modules/index.ts
Auto-merging src/shared/types/dash.ts
CONFLICT (add/add): Merge conflict in src/shared/types/dash.ts
Auto-merging src/shared/types/feature.ts
CONFLICT (add/add): Merge conflict in src/shared/types/feature.ts
Auto-merging src/shared/types/wizard/index.ts
CONFLICT (add/add): Merge conflict in src/shared/types/wizard/index.ts
Auto-merging src/ui/components/DashKit/plugins/Control/Control.tsx
CONFLICT (add/add): Merge conflict in src/ui/components/DashKit/plugins/Control/Control.tsx
Auto-merging src/ui/components/DashKit/plugins/Control/utils.ts
CONFLICT (add/add): Merge conflict in src/ui/components/DashKit/plugins/Control/utils.ts
Auto-merging src/ui/components/EntryContextMenu/constants.ts
CONFLICT (add/add): Merge conflict in src/ui/components/EntryContextMenu/constants.ts
Auto-merging src/ui/components/common/Datepicker/Datepicker.js
CONFLICT (add/add): Merge conflict in src/ui/components/common/Datepicker/Datepicker.js
Auto-merging src/ui/constants/connections.ts
CONFLICT (add/add): Merge conflict in src/ui/constants/connections.ts
Auto-merging src/ui/constants/visualizations/line.ts
CONFLICT (add/add): Merge conflict in src/ui/constants/visualizations/line.ts
Auto-merging src/ui/constants/visualizations/scatter.ts
CONFLICT (add/add): Merge conflict in src/ui/constants/visualizations/scatter.ts
Auto-merging src/ui/libs/DatalensChartkit/ChartKit/helpers/action-params-handlers.ts
CONFLICT (add/add): Merge conflict in src/ui/libs/DatalensChartkit/ChartKit/helpers/action-params-handlers.ts
Auto-merging src/ui/libs/DatalensChartkit/ChartKit/helpers/apply-hc-handlers.ts
CONFLICT (add/add): Merge conflict in src/ui/libs/DatalensChartkit/ChartKit/helpers/apply-hc-handlers.ts
Auto-merging src/ui/libs/DatalensChartkit/components/Control/Control.tsx
CONFLICT (add/add): Merge conflict in src/ui/libs/DatalensChartkit/components/Control/Control.tsx
Auto-merging src/ui/libs/DatalensChartkit/components/Control/Items/Items.js
CONFLICT (add/add): Merge conflict in src/ui/libs/DatalensChartkit/components/Control/Items/Items.js
Auto-merging src/ui/libs/DatalensChartkit/modules/data-provider/charts/index.ts
CONFLICT (add/add): Merge conflict in src/ui/libs/DatalensChartkit/modules/data-provider/charts/index.ts
Auto-merging src/ui/libs/DatalensChartkit/modules/datalens-chartkit-custom-error/datalens-chartkit-custom-error.ts
CONFLICT (add/add): Merge conflict in src/ui/libs/DatalensChartkit/modules/datalens-chartkit-custom-error/datalens-chartkit-custom-error.ts
Auto-merging src/ui/units/connections/components/Page/utils.ts
CONFLICT (add/add): Merge conflict in src/ui/units/connections/components/Page/utils.ts
Auto-merging src/ui/units/connections/components/custom-forms/Yadocs/components/DialogAddDocument/DialogAddDocument.tsx
CONFLICT (add/add): Merge conflict in src/ui/units/connections/components/custom-forms/Yadocs/components/DialogAddDocument/DialogAddDocument.tsx
Auto-merging src/ui/units/connections/constants/index.ts
CONFLICT (add/add): Merge conflict in src/ui/units/connections/constants/index.ts
Auto-merging src/ui/units/dash/containers/Dialogs/DialogRelations/components/Content/Row.tsx
CONFLICT (add/add): Merge conflict in src/ui/units/dash/containers/Dialogs/DialogRelations/components/Content/Row.tsx
Auto-merging src/ui/units/dash/containers/Dialogs/DialogRelations/hooks/helpers.ts
CONFLICT (add/add): Merge conflict in src/ui/units/dash/containers/Dialogs/DialogRelations/hooks/helpers.ts
Auto-merging src/ui/units/wizard/actions/dialog.ts
CONFLICT (add/add): Merge conflict in src/ui/units/wizard/actions/dialog.ts
Auto-merging src/ui/units/wizard/actions/placeholder.ts
CONFLICT (add/add): Merge conflict in src/ui/units/wizard/actions/placeholder.ts
Auto-merging src/ui/units/wizard/components/Dialogs/DialogColor/ColorSettingsContainer/ColorSettingsContainer.tsx
CONFLICT (add/add): Merge conflict in src/ui/units/wizard/components/Dialogs/DialogColor/ColorSettingsContainer/ColorSettingsContainer.tsx
Auto-merging src/ui/units/wizard/components/Dialogs/DialogColor/DialogColor.tsx
CONFLICT (add/add): Merge conflict in src/ui/units/wizard/components/Dialogs/DialogColor/DialogColor.tsx
Auto-merging src/ui/units/wizard/components/Dialogs/DialogColor/DialogColorPalette/DialogColorPalette.tsx
CONFLICT (add/add): Merge conflict in src/ui/units/wizard/components/Dialogs/DialogColor/DialogColorPalette/DialogColorPalette.tsx
Auto-merging src/ui/units/wizard/components/ValuesList/ValuesList.tsx
CONFLICT (add/add): Merge conflict in src/ui/units/wizard/components/ValuesList/ValuesList.tsx
Auto-merging src/ui/units/wizard/containers/Wizard/SectionVisualization/PlaceholdersContainer/ColorsPlaceholder/ColorsPlaceholder.tsx
CONFLICT (add/add): Merge conflict in src/ui/units/wizard/containers/Wizard/SectionVisualization/PlaceholdersContainer/ColorsPlaceholder/ColorsPlaceholder.tsx
Auto-merging src/ui/units/workbooks/components/EntryActions/EntryActions.tsx
CONFLICT (add/add): Merge conflict in src/ui/units/workbooks/components/EntryActions/EntryActions.tsx
Auto-merging tests/docker-compose.e2e.yml
CONFLICT (add/add): Merge conflict in tests/docker-compose.e2e.yml
Auto-merging tests/page-objects/wizard/SectionVisualization.ts
CONFLICT (add/add): Merge conflict in tests/page-objects/wizard/SectionVisualization.ts
error: could not apply 56f509ac... Add link to Yandex Documents in DialogAddDocument
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 56f509ac... Add link to Yandex Documents in DialogAddDocument
 (1)
```
</details>
**Resolve conflicts according to instructions**
1. Switch to the current branch associated with this pull request.
```
git checkout add-link-to-yadocs
```
2. Add Weblate as remote:
```
git remote add weblate https://weblate.gravity-ui.com/git/datalens/add-link-to-yadocs-530/chartkit-530/
git remote update weblate
```
3. Merge Weblate changes:
```
git merge weblate/add-link-to-yadocs
```
4. Resolve conflicts:
```
edit ...
git add ...
git commit
```
5. Push changes to upstream repository, Weblate will fetch merge from there:
```
git push origin
```

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/add-link-to-yadocs-530/component-dialog-relations-view-530/en/">component.dialog-relations.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/add-link-to-yadocs-530/component-dialog-relations-view-530/ru/">component.dialog-relations.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by Marginy605 — APPROVED** [review]

**Pull request merged**
