### PR TITLE
withoutSidebar, enableAutoheight, enableBackgroundColor for DialogChartWidget

### PR DESCRIPTION
**Pull request by artemipanchuk**
image

image

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10126-1421/dash-widget-dialog-edit-1421/ru/">dash.widget-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10126-1421/dash-widget-dialog-edit-1421/en/">dash.widget-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10126-1421/dash-widget-dialog-edit-1421/ru/">dash.widget-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10126-1421/dash-widget-dialog-edit-1421/en/">dash.widget-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by flops — APPROVED** [review]

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10126-1421/dash-widget-dialog-edit-1421/ru/">dash.widget-dialog.edit (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by flops — APPROVED** [review]

**Comment by artemipanchuk** [comment]
1 E2E test with YT flapped

**Pull request merged**
