### PR TITLE
Toggle dataset preview by default

### PR DESCRIPTION
**Pull request by flops**
image

Toggle dataset preview loading settings by default.

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9665-toggle-dataset-preview-by-default-1046/dataset-dataset-editor-modify-1046/ru/">dataset.dataset-editor.modify (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9665-toggle-dataset-preview-by-default-1046/dataset-dataset-editor-modify-1046/en/">dataset.dataset-editor.modify (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9665-toggle-dataset-preview-by-default-1046/dataset-dataset-editor-modify-1046/ru/">dataset.dataset-editor.modify (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9665-toggle-dataset-preview-by-default-1046/dataset-dataset-editor-modify-1046/en/">dataset.dataset-editor.modify (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9665-toggle-dataset-preview-by-default-1046/dataset-dataset-editor-modify-1046/ru/">dataset.dataset-editor.modify (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9665-toggle-dataset-preview-by-default-1046/dataset-dataset-editor-modify-1046/en/">dataset.dataset-editor.modify (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9665-toggle-dataset-preview-by-default-1046/dataset-dataset-editor-modify-1046/ru/">dataset.dataset-editor.modify (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9665-toggle-dataset-preview-by-default-1046/dataset-dataset-editor-modify-1046/en/">dataset.dataset-editor.modify (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9665-toggle-dataset-preview-by-default-1046/dataset-dataset-editor-modify-1046/ru/">dataset.dataset-editor.modify (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9665-toggle-dataset-preview-by-default-1046/dataset-dataset-editor-modify-1046/en/">dataset.dataset-editor.modify (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by korvin89 — APPROVED** [review]

**Pull request merged**
