### PR TITLE
Dialog relations fix & improve disconnect action

### PR DESCRIPTION
**Pull request by Marginy605**
- Removed beta mark
- Add disconnection by type switcher
- Fixed tests
- Fix alias modal width

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9220-ignore-all-improvements-669/component-dialog-relations-view-669/ru/">component.dialog-relations.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9220-ignore-all-improvements-669/component-dialog-relations-view-669/en/">component.dialog-relations.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>Errors occurred when merging changes from your branch with the Weblate branch.</summary>

```
Rebasing (1/2)
Auto-merging src/ui/units/dash/containers/Dialogs/DialogRelations/DialogRelations.tsx
CONFLICT (content): Merge conflict in src/ui/units/dash/containers/Dialogs/DialogRelations/DialogRelations.tsx
error: could not apply 24c78147... Fix typing
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 24c78147... Fix typing
 (1)
```

</details>

**Resolve conflicts according to instructions**
1. Switch to the current branch associated with this pull request.
```
git checkout CHARTS-9220-ignore-all-improvements
```
2. Add Weblate as remote. And remove previous upstream with the same name:
```
git remote remove weblate 2> /dev/null
git remote add weblate https://weblate.gravity-ui.com/git/datalens/charts-9220-ignore-all-improvements-669/chartkit-669/
git -c http.sslVerify=false remote update weblate
```
3. Merge Weblate changes:
```
git merge weblate/CHARTS-9220-ignore-all-improvements
```
4. Resolve conflicts:
```
edit ...
git add ...
git commit
```
5. Push changes to upstream repository, Weblate will fetch merge from there:
```
git push origin
```

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9220-ignore-all-improvements-669/component-dialog-relations-view-669/ru/">component.dialog-relations.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9220-ignore-all-improvements-669/component-dialog-relations-view-669/en/">component.dialog-relations.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9220-ignore-all-improvements-669/component-dialog-relations-view-669/ru/">component.dialog-relations.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9220-ignore-all-improvements-669/component-dialog-relations-view-669/en/">component.dialog-relations.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9220-ignore-all-improvements-669/component-dialog-relations-view-669/ru/">component.dialog-relations.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9220-ignore-all-improvements-669/component-dialog-relations-view-669/en/">component.dialog-relations.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9220-ignore-all-improvements-669/component-dialog-relations-view-669/ru/">component.dialog-relations.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9220-ignore-all-improvements-669/component-dialog-relations-view-669/en/">component.dialog-relations.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Review by mournfulCoroner — APPROVED** [review]

**Pull request merged**
