### PR TITLE
Add error message for case when connection failed to load

### PR DESCRIPTION
**Pull request by artemipanchuk**

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/sql-500/en/">sql (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/sql-500/ru/">sql (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/temp-500/en/">temp (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/temp-500/ru/">temp (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>Errors occurred when merging changes from your branch with the Weblate branch.</summary>
```
Rebasing (1/1)
Auto-merging src/i18n-keysets/sql/en.json
CONFLICT (content): Merge conflict in src/i18n-keysets/sql/en.json
error: could not apply 8c63fb7... Translated using Weblate (Russian)
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 8c63fb7... Translated using Weblate (Russian)
 (1)
```
</details>
**Resolve conflicts according to instructions**
1. Switch to the current branch associated with this pull request.
```
git checkout apanchuk-CHARTS-8911
```
2. Add Weblate as remote:
```
git remote add weblate https://weblate.gravity-ui.com/git/datalens/apanchuk-charts-8911-500/chartkit-500/
git remote update weblate
```
3. Merge Weblate changes:
```
git merge weblate/apanchuk-CHARTS-8911
```
4. Resolve conflicts:
```
edit ...
git add ...
git commit
```
5. Push changes to upstream repository, Weblate will fetch merge from there:
```
git push origin
```

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/collections-500/en/">collections (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/collections-500/ru/">collections (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/components-common-datepicker-500/en/">components.common.Datepicker (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/components-common-datepicker-500/ru/">components.common.Datepicker (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/connections-yadocs-view-500/en/">connections.yadocs.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/connections-yadocs-view-500/ru/">connections.yadocs.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/dash-control-dialog-edit-500/en/">dash.control-dialog.edit (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/dash-control-dialog-edit-500/ru/">dash.control-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/dash-dashkit-plugin-control-view-500/en/">dash.dashkit-plugin-control.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/dash-dashkit-plugin-control-view-500/ru/">dash.dashkit-plugin-control.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/sql-500/en/">sql (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/sql-500/ru/">sql (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/sql-500/en/">sql (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-8911-500/sql-500/ru/">sql (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by kuzmadom — APPROVED** [review]

**Pull request merged**
