### PR TITLE
Use local chart editor templates

### PR DESCRIPTION
**Pull request by artemipanchuk**
Now templates for chart editor are stored in code base

Also templates in editor ui now are opening instantly, instead of being loaded

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-relations-view-606/en/">component.dialog-relations.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-relations-view-606/ru/">component.dialog-relations.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-relations-view-606/en/">component.dialog-relations.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-relations-view-606/ru/">component.dialog-relations.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-relations-view-606/en/">component.dialog-relations.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-relations-view-606/ru/">component.dialog-relations.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-relations-view-606/en/">component.dialog-relations.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-relations-view-606/ru/">component.dialog-relations.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-relations-view-606/en/">component.dialog-relations.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-relations-view-606/ru/">component.dialog-relations.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-switch-public-view-606/ru/">component.dialog-switch-public.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/new-workbooks-606/ru/">new-workbooks (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-relations-view-606/en/">component.dialog-relations.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-relations-view-606/ru/">component.dialog-relations.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/component-dialog-switch-public-view-606/ru/">component.dialog-switch-public.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/new-workbooks-606/ru/">new-workbooks (ru)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/ru/">editor.templates.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/apanchuk-charts-9087-606/editor-templates-view-606/en/">editor.templates.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by korvin89 — APPROVED** [review]

**Review by korvin89 — APPROVED** [review]

**Comment by artemipanchuk** [comment]
Related to https://github.com/datalens-tech/datalens/issues/92

**Comment by artemipanchuk** [comment]
Related to https://github.com/datalens-tech/datalens/issues/94

**Pull request merged**
