### PR TITLE
Support mobile in workbook page

### PR DESCRIPTION
**Pull request by mournfulCoroner**

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9637-mobile-workbook-page-1059/new-workbooks-1059/ru/">new-workbooks (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9637-mobile-workbook-page-1059/new-workbooks-1059/en/">new-workbooks (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by flops — APPROVED** [review]

**Comment by mournfulCoroner** [comment]
Related to https://github.com/datalens-tech/datalens/issues/85

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9637-mobile-workbook-page-1059/new-workbooks-1059/ru/">new-workbooks (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9637-mobile-workbook-page-1059/new-workbooks-1059/en/">new-workbooks (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9637-mobile-workbook-page-1059/new-workbooks-1059/ru/">new-workbooks (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9637-mobile-workbook-page-1059/new-workbooks-1059/en/">new-workbooks (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by Sergey-weber — DISMISSED** [review]

**Review by flops — DISMISSED** [review]

**Review by flops — APPROVED** [review]

**Pull request merged**
