### PR TITLE
Fix error of selector execution

### PR DESCRIPTION
**Pull request by mournfulCoroner**

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9794-fix-editor-selector-error-1110/chartkit-control-1110/ru/">chartkit.control (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9794-fix-editor-selector-error-1110/chartkit-control-1110/en/">chartkit.control (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9794-fix-editor-selector-error-1110/wizard-1110/ru/">wizard (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9794-fix-editor-selector-error-1110/wizard-1110/en/">wizard (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>Errors occurred when merging changes from your branch with the Weblate branch.</summary>

```
Rebasing (1/1)
Auto-merging src/ui/libs/DatalensChartkit/components/Control/Control.scss
CONFLICT (add/add): Merge conflict in src/ui/libs/DatalensChartkit/components/Control/Control.scss
error: could not apply 81cad8bd... Fix error of selector execution
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 81cad8bd... Fix error of selector execution
 (1)
```

</details>

**Resolve conflicts according to instructions**
1. Switch to the current branch associated with this pull request.
```
git checkout CHARTS-9794-Fix-editor-selector-error
```
2. Add Weblate as remote. And remove previous upstream with the same name:
```
git remote remove weblate 2> /dev/null
git remote add weblate https://weblate.gravity-ui.com/git/datalens/charts-9794-fix-editor-selector-error-1110/chartkit-1110/
git -c http.sslVerify=false remote update weblate
```
3. Merge Weblate changes:
```
git merge weblate/CHARTS-9794-Fix-editor-selector-error
```
4. Resolve conflicts:
```
edit ...
git add ...
git commit
```
5. Push changes to upstream repository, Weblate will fetch merge from there:
```
git push origin
```

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>Errors occurred when merging changes from your branch with the Weblate branch.</summary>

```
Rebasing (1/1)
Auto-merging dev/env/opensource/development.env
CONFLICT (add/add): Merge conflict in dev/env/opensource/development.env
Auto-merging src/@types/nodekit.d.ts
CONFLICT (add/add): Merge conflict in src/@types/nodekit.d.ts
Auto-merging src/i18n-keysets/wizard/en.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/wizard/en.json
Auto-merging src/i18n-keysets/wizard/ru.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/wizard/ru.json
Auto-merging src/server/components/features/features-list/WorkerChartBuilder.ts
CONFLICT (add/add): Merge conflict in src/server/components/features/features-list/WorkerChartBuilder.ts
Auto-merging src/server/components/zitadel/init-zitadel.ts
CONFLICT (add/add): Merge conflict in src/server/components/zitadel/init-zitadel.ts
Auto-merging src/server/components/zitadel/utils.ts
CONFLICT (add/add): Merge conflict in src/server/components/zitadel/utils.ts
Auto-merging src/server/configs/opensource/common.ts
CONFLICT (add/add): Merge conflict in src/server/configs/opensource/common.ts
Auto-merging src/shared/modules/helpers.ts
CONFLICT (add/add): Merge conflict in src/shared/modules/helpers.ts
Auto-merging src/shared/types/feature.ts
CONFLICT (add/add): Merge conflict in src/shared/types/feature.ts
Auto-merging src/shared/types/wizard/field.ts
CONFLICT (add/add): Merge conflict in src/shared/types/wizard/field.ts
Auto-merging src/shared/types/wizard/misc.ts
CONFLICT (add/add): Merge conflict in src/shared/types/wizard/misc.ts
Auto-merging src/ui/constants/visualizations/pivotTable.ts
CONFLICT (add/add): Merge conflict in src/ui/constants/visualizations/pivotTable.ts
Auto-merging src/ui/libs/DatalensChartkit/components/Control/Control.scss
CONFLICT (add/add): Merge conflict in src/ui/libs/DatalensChartkit/components/Control/Control.scss
Auto-merging src/ui/units/wizard/components/Dialogs/DialogField/DialogField.tsx
CONFLICT (add/add): Merge conflict in src/ui/units/wizard/components/Dialogs/DialogField/DialogField.tsx
Auto-merging src/ui/units/wizard/components/Dialogs/DialogField/utils/misc.ts
CONFLICT (add/add): Merge conflict in src/ui/units/wizard/components/Dialogs/DialogField/utils/misc.ts
Auto-merging src/ui/units/wizard/containers/Wizard/SectionVisualization/VisualizationItem/VisualizationItem.tsx
CONFLICT (add/add): Merge conflict in src/ui/units/wizard/containers/Wizard/SectionVisualization/VisualizationItem/VisualizationItem.tsx
Auto-merging src/ui/units/wizard/utils/helpers.ts
CONFLICT (add/add): Merge conflict in src/ui/units/wizard/utils/helpers.ts
error: could not apply 81cad8bd... Fix error of selector execution
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 81cad8bd... Fix error of selector execution
 (1)
```

</details>

**Resolve conflicts according to instructions**
1. Switch to the current branch associated with this pull request.
```
git checkout CHARTS-9794-Fix-editor-selector-error
```
2. Add Weblate as remote. And remove previous upstream with the same name:
```
git remote remove weblate 2> /dev/null
git remote add weblate https://weblate.gravity-ui.com/git/datalens/charts-9794-fix-editor-selector-error-1110/chartkit-1110/
git -c http.sslVerify=false remote update weblate
```
3. Merge Weblate changes:
```
git merge weblate/CHARTS-9794-Fix-editor-selector-error
```
4. Resolve conflicts:
```
edit ...
git add ...
git commit
```
5. Push changes to upstream repository, Weblate will fetch merge from there:
```
git push origin
```

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9794-fix-editor-selector-error-1110/chartkit-control-1110/ru/">chartkit.control (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9794-fix-editor-selector-error-1110/chartkit-control-1110/en/">chartkit.control (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9794-fix-editor-selector-error-1110/wizard-1110/ru/">wizard (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9794-fix-editor-selector-error-1110/wizard-1110/en/">wizard (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9794-fix-editor-selector-error-1110/chartkit-control-1110/ru/">chartkit.control (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9794-fix-editor-selector-error-1110/chartkit-control-1110/en/">chartkit.control (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by flops — APPROVED** [review]

**Pull request merged**
