### PR TITLE
Add dataset optimize join(required) field

### PR DESCRIPTION
**Pull request by flops**

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/connections-yadocs-view-810/ru/">connections.yadocs.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/connections-yadocs-view-810/en/">connections.yadocs.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dash-dialogs-common-edit-810/ru/">dash.dialogs-common.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dash-dialogs-common-edit-810/en/">dash.dialogs-common.edit (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dataset-sources-tab-modify-810/ru/">dataset.sources-tab.modify (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dataset-sources-tab-modify-810/en/">dataset.sources-tab.modify (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/editor-templates-view-810/ru/">editor.templates.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/editor-templates-view-810/en/">editor.templates.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/connections-yadocs-view-810/ru/">connections.yadocs.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/connections-yadocs-view-810/en/">connections.yadocs.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dash-dialogs-common-edit-810/ru/">dash.dialogs-common.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dash-dialogs-common-edit-810/en/">dash.dialogs-common.edit (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dataset-sources-tab-modify-810/ru/">dataset.sources-tab.modify (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dataset-sources-tab-modify-810/en/">dataset.sources-tab.modify (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/editor-templates-view-810/ru/">editor.templates.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/editor-templates-view-810/en/">editor.templates.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/connections-yadocs-view-810/ru/">connections.yadocs.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/connections-yadocs-view-810/en/">connections.yadocs.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dash-dialogs-common-edit-810/ru/">dash.dialogs-common.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dash-dialogs-common-edit-810/en/">dash.dialogs-common.edit (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dataset-sources-tab-modify-810/ru/">dataset.sources-tab.modify (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dataset-sources-tab-modify-810/en/">dataset.sources-tab.modify (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/editor-templates-view-810/ru/">editor.templates.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/editor-templates-view-810/en/">editor.templates.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dataset-sources-tab-modify-810/ru/">dataset.sources-tab.modify (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9327-dataset-avatar-required-field-810/dataset-sources-tab-modify-810/en/">dataset.sources-tab.modify (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by korvin89 — APPROVED** [review]

**Pull request merged**
