### PR TITLE
Compact tooltip in maps

### PR DESCRIPTION
**Pull request by kuzmadom**
Added the ability to disable the color indicator and field names in map tooltips

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10310-1546/wizard-1546/ru/">wizard (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10310-1546/wizard-1546/en/">wizard (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10310-1546/wizard-1546/ru/">wizard (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10310-1546/wizard-1546/en/">wizard (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10310-1546/wizard-1546/ru/">wizard (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10310-1546/wizard-1546/en/">wizard (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10310-1546/wizard-1546/ru/">wizard (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10310-1546/wizard-1546/en/">wizard (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10310-1546/wizard-1546/ru/">wizard (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10310-1546/wizard-1546/en/">wizard (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10310-1546/wizard-1546/en/">wizard (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by artemipanchuk — APPROVED** [review]

**Pull request merged**
