### PR TITLE
Hierarchy chart warning

### PR DESCRIPTION
**Pull request by flops**

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9395-hierarchy-chart-warning-850/dash-widget-dialog-edit-850/ru/">dash.widget-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9395-hierarchy-chart-warning-850/dash-widget-dialog-edit-850/en/">dash.widget-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9395-hierarchy-chart-warning-850/dash-widget-dialog-edit-850/ru/">dash.widget-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9395-hierarchy-chart-warning-850/dash-widget-dialog-edit-850/en/">dash.widget-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9395-hierarchy-chart-warning-850/dash-widget-dialog-edit-850/ru/">dash.widget-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9395-hierarchy-chart-warning-850/dash-widget-dialog-edit-850/en/">dash.widget-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9395-hierarchy-chart-warning-850/dash-widget-dialog-edit-850/ru/">dash.widget-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9395-hierarchy-chart-warning-850/dash-widget-dialog-edit-850/en/">dash.widget-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9395-hierarchy-chart-warning-850/dash-widget-dialog-edit-850/ru/">dash.widget-dialog.edit (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9395-hierarchy-chart-warning-850/dash-widget-dialog-edit-850/en/">dash.widget-dialog.edit (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by mournfulCoroner — APPROVED** [review]

**Pull request merged**
