### PR TITLE
Add widget background like chart

### PR DESCRIPTION
**Pull request by Marginy605**
image

Related to https://github.com/datalens-tech/datalens/issues/104

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9670-add-same-chart-bg-1099/dash-palette-background-1099/ru/">dash.palette-background (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9670-add-same-chart-bg-1099/dash-palette-background-1099/en/">dash.palette-background (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9670-add-same-chart-bg-1099/dash-palette-background-1099/ru/">dash.palette-background (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9670-add-same-chart-bg-1099/dash-palette-background-1099/en/">dash.palette-background (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9670-add-same-chart-bg-1099/dash-palette-background-1099/ru/">dash.palette-background (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9670-add-same-chart-bg-1099/dash-palette-background-1099/en/">dash.palette-background (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Review by mournfulCoroner — APPROVED** [review]

**Comment by Marginy605** [comment]
Flacky tests, not connected with changes:
image

**Pull request merged**
