### PR TITLE
Add tooltip for checkbox in flat list for workbook entries

### PR DESCRIPTION
**Pull request by Sergey-weber**
Add tooltip for checkbox in flat list for workbook entries
Add disabled state for workbook entries in flat list
Hide checkbox when isOnlyCollectionsMode

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
The reviewer is still working on checking your i18n changes. Wait for a Pull Request from Weblate.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Comment by robot-charts** [comment]
**i18n-check**
Please merge the Pull Request with the changes from Weblate into your branch.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10263-disable-checkbox-for-workbook-entries-in-navigation-1594/component-navigation-view-1594/ru/">component.navigation.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10263-disable-checkbox-for-workbook-entries-in-navigation-1594/component-navigation-view-1594/en/">component.navigation.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10263-disable-checkbox-for-workbook-entries-in-navigation-1594/component-navigation-view-1594/ru/">component.navigation.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-10263-disable-checkbox-for-workbook-entries-in-navigation-1594/component-navigation-view-1594/en/">component.navigation.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by jhoncool — APPROVED** [review]

**Pull request merged**
