### PR TITLE
Add dash deprecation warnings and dependentSelectors true when copy 

### PR DESCRIPTION
**Pull request by flops**

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-revisions-panel-view-819/ru/">component.revisions-panel.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-revisions-panel-view-819/en/">component.revisions-panel.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/dash-action-panel-view-819/ru/">dash.action-panel.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/dash-action-panel-view-819/en/">dash.action-panel.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-revisions-panel-view-819/ru/">component.revisions-panel.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-revisions-panel-view-819/en/">component.revisions-panel.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/dash-action-panel-view-819/ru/">dash.action-panel.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/dash-action-panel-view-819/en/">dash.action-panel.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-dialog-copy-entry-view-819/ru/">component.dialog-copy-entry.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-dialog-copy-entry-view-819/en/">component.dialog-copy-entry.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-revisions-panel-view-819/ru/">component.revisions-panel.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-revisions-panel-view-819/en/">component.revisions-panel.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/dash-action-panel-view-819/ru/">dash.action-panel.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/dash-action-panel-view-819/en/">dash.action-panel.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-dialog-copy-entry-view-819/ru/">component.dialog-copy-entry.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-dialog-copy-entry-view-819/en/">component.dialog-copy-entry.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-revisions-panel-view-819/ru/">component.revisions-panel.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-revisions-panel-view-819/en/">component.revisions-panel.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/dash-action-panel-view-819/ru/">dash.action-panel.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/dash-action-panel-view-819/en/">dash.action-panel.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-dialog-copy-entry-view-819/ru/">component.dialog-copy-entry.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-dialog-copy-entry-view-819/en/">component.dialog-copy-entry.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-revisions-panel-view-819/ru/">component.revisions-panel.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-revisions-panel-view-819/en/">component.revisions-panel.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/dash-action-panel-view-819/ru/">dash.action-panel.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/dash-action-panel-view-819/en/">dash.action-panel.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-dialog-copy-entry-view-819/ru/">component.dialog-copy-entry.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-dialog-copy-entry-view-819/en/">component.dialog-copy-entry.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-revisions-panel-view-819/ru/">component.revisions-panel.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/component-revisions-panel-view-819/en/">component.revisions-panel.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/dash-action-panel-view-819/ru/">dash.action-panel.view (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9406-dependent-selectors-via-mix-true-819/dash-action-panel-view-819/en/">dash.action-panel.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by Marginy605 — APPROVED** [review]

**Pull request merged**
