### PR TITLE
Add custom error for workbook isolation interruption

### PR DESCRIPTION
**Pull request by imsitnikov**

### CODE REVIEW

**Review by korvin89 — DISMISSED** [review]

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/component-chartkit-error-codes-630/ru/">component.chartkit-error.codes (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/component-chartkit-error-codes-630/en/">component.chartkit-error.codes (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/component-chartkit-error-codes-630/ru/">component.chartkit-error.codes (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/component-chartkit-error-codes-630/en/">component.chartkit-error.codes (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/dash-dashkit-plugin-control-view-630/en/">dash.dashkit-plugin-control.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/dash-dashkit-plugin-control-view-630/en/">dash.dashkit-plugin-control.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/dash-dashkit-plugin-control-view-630/en/">dash.dashkit-plugin-control.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/connections-form-630/ru/">connections.form (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/connections-form-630/en/">connections.form (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/dash-dashkit-plugin-control-view-630/en/">dash.dashkit-plugin-control.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/connections-form-630/ru/">connections.form (ru)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/connections-form-630/en/">connections.form (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-custom-workbook-isolation-error-630/dash-dashkit-plugin-control-view-630/en/">dash.dashkit-plugin-control.view (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Review by korvin89 — APPROVED** [review]

**Pull request merged**
