### PR TITLE
Add missing key

### PR DESCRIPTION
**Pull request by Marginy605**

### CODE REVIEW

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-fix-keyset-635/component-dialog-copy-entry-view-635/en/">component.dialog-copy-entry.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-fix-keyset-635/connections-form-635/en/">connections.form (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>Errors occurred when merging changes from your branch with the Weblate branch.</summary>

```
Rebasing (1/1)
Auto-merging src/i18n-keysets/connections.form/en.json
CONFLICT (add/add): Merge conflict in src/i18n-keysets/connections.form/en.json
error: could not apply d79e1af3... Add missing key
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply d79e1af3... Add missing key
 (1)
```

</details>

**Resolve conflicts according to instructions**
1. Switch to the current branch associated with this pull request.
```
git checkout CHARTS-9189-fix-keyset
```
2. Add Weblate as remote. And remove previous upstream with the same name:
```
git remote remove weblate 2> /dev/null
git remote add weblate https://weblate.gravity-ui.com/git/datalens/charts-9189-fix-keyset-635/chartkit-635/
git -c http.sslVerify=false remote update weblate
```
3. Merge Weblate changes:
```
git merge weblate/CHARTS-9189-fix-keyset
```
4. Resolve conflicts:
```
edit ...
git add ...
git commit
```
5. Push changes to upstream repository, Weblate will fetch merge from there:
```
git push origin
```

**Comment by robot-charts** [comment]
**i18n-check**
<details>
<summary>The following components have not been translated</summary>
<p><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-fix-keyset-635/component-dialog-copy-entry-view-635/en/">component.dialog-copy-entry.view (en)</a><br><a href="https://weblate.gravity-ui.com/projects/datalens/charts-9189-fix-keyset-635/connections-form-635/en/">connections.form (en)</a></p>
</details>

Wait for the reviewers to check your changes in Weblate and try running github action again.

**Comment by Marginy605** [comment]
There is no need to wait for e2e tests: empty keysets was replaced with translations

**Review by mournfulCoroner — APPROVED** [review]

**Pull request merged**
